import RSS from 'rss';
import { NotFoundError } from '../errors/index.js';
import config from '../config/index.js';
import logger from '../logger/index.js';

export class RSSPlugin {
  constructor(registry) {
    this.manifest = {
      name: 'rss',
      version: '1.0.0',
      category: 'rss',
      description: 'RSS feed generator for scraped data',
      author: 'OmniScraper',
      endpoints: ['/api/v1/rss/:source', '/api/v1/rss/:source/:category'],
      dependencies: ['rss']
    };
    this.registry = registry;
    this.feeds = new Map();
  }

  generateFeed(meta) {
    return new RSS({
      title: meta.title || 'OmniScraper Feed',
      description: meta.description || 'Generated by OmniScraper',
      feed_url: meta.feedUrl || 'http://localhost:3000/api/v1/rss',
      site_url: meta.siteUrl || 'http://localhost:3000',
      image_url: meta.imageUrl,
      language: meta.language || 'en',
      pubDate: new Date(),
      ttl: meta.ttl || 60
    });
  }

  async generateIMDBFeed(type = 'top') {
    const imdb = this.registry.get('imdb');
    if (!imdb) throw new NotFoundError('IMDB plugin');

    const feed = this.generateFeed({
      title: `IMDB ${type} Movies`,
      description: `Top ${type} movies from IMDB`,
      feedUrl: `http://localhost:3000/api/v1/rss/imdb/${type}`
    });

    if (type === 'top') {
      const movies = await imdb.getTopMovies(50);
      for (const movie of movies) {
        feed.item({
          title: movie.title,
          description: `Rating: ${movie.rating} | Rank: ${movie.rank}`,
          url: movie.url,
          guid: movie.url,
          date: new Date()
        });
      }
    }

    return feed.xml();
  }

  async generateUniversalFeed(scraperName) {
    const universal = this.registry.get('universal');
    if (!universal) throw new NotFoundError('Universal plugin');

    const definition = universal.scrapers.get(scraperName);
    if (!definition) throw new NotFoundError(`Scraper ${scraperName}`);

    const feed = this.generateFeed({
      title: `${scraperName} Feed`,
      description: definition.description || `Feed from ${scraperName}`,
      feedUrl: `http://localhost:3000/api/v1/rss/universal/${scraperName}`
    });

    if (definition.baseUrl) {
      const data = await universal.runScraper(scraperName, definition.baseUrl);
      feed.item({
        title: data.title || scraperName,
        description: JSON.stringify(data),
        url: definition.baseUrl,
        guid: definition.baseUrl,
        date: new Date()
      });
    }

    return feed.xml();
  }

  async generateMusicFeed() {
    const music = this.registry.get('music');
    if (!music) throw new NotFoundError('Music plugin');

    const feed = this.generateFeed({
      title: 'Now Playing Music',
      description: 'Music now playing and recent tracks',
      feedUrl: 'http://localhost:3000/api/v1/rss/music'
    });

    for (const entry of music.history.slice(0, 50)) {
      feed.item({
        title: `${entry.track} - ${entry.artist}`,
        description: `Album: ${entry.album || 'Unknown'}`,
        url: entry.url || '',
        guid: `${entry.source}_${entry.timestamp}`,
        date: new Date(entry.timestamp)
      });
    }

    return feed.xml();
  }

  async generateTorrentFeed() {
    const torrent = this.registry.get('torrent');
    if (!torrent) throw new NotFoundError('Torrent plugin');

    const feed = this.generateFeed({
      title: 'Active Torrents',
      description: 'Currently active torrents',
      feedUrl: 'http://localhost:3000/api/v1/rss/torrent'
    });

    const torrents = torrent.getActiveTorrents();
    for (const t of torrents) {
      feed.item({
        title: t.name,
        description: `Progress: ${(t.progress * 100).toFixed(1)}% | Peers: ${t.numPeers}`,
        guid: t.infoHash,
        date: new Date()
      });
    }

    return feed.xml();
  }

  async getFeed(source, category) {
    const cacheKey = `rss_${source}_${category || 'all'}`;
    const cached = this.feeds.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < 300000) {
      return cached.data;
    }

    let xml;
    switch (source) {
      case 'imdb':
        xml = await this.generateIMDBFeed(category || 'top');
        break;
      case 'universal':
        xml = await this.generateUniversalFeed(category);
        break;
      case 'music':
        xml = await this.generateMusicFeed();
        break;
      case 'torrent':
        xml = await this.generateTorrentFeed();
        break;
      default:
        throw new NotFoundError(`Feed source: ${source}`);
    }

    this.feeds.set(cacheKey, { data: xml, timestamp: Date.now() });
    return xml;
  }

  async start() { logger.info('RSS plugin started'); }
  async stop() { this.feeds.clear(); }
  async destroy() { this.feeds.clear(); }
}

export default RSSPlugin;
